### ISSUE TITLE
Using translocator makes flag be dropped

### ISSUE THREAD

**Issue by ObaniGemini** [dnk777/wtf#1]
When using *runner* class, the flag is dropped while teleporting with *translocator*.
I don't think it is intended, it is ? If yes it would probably be less confusing just to disable using translocator

**Comment by dnk777** [comment]
It IS intended https://github.com/dnk777/wtf/blob/master/gametypes/wtf/wtf_players.as#L676.
I do not think translocator usage should be disabled for a flag carrier. Sometimes a flag carrier wants to use it even at cost of flag drop (especially when a flag drop means nothing, e.g. he's hiding in his own base and wants to grab an item reachable only with a translocator and grab the flag back). He might use `drop flag` bind to enable translocation, but I rather prefer to keep this behavior that is familiar to any person that have played Unreal Tournament.

And also I think regular teleporters should behave like this to ease flag carrier chasing (as in UT too). This, however, requires moving teleporters handling from native code to scripts.

**Comment by dnk777** [comment]
Actually one needs to ADD some pieces of code to enable the current behavior, like I did. An attached flag is not an item but an effect bit added to a client IIRC (flag effect is hardcoded into the engine), and the «flag» gets teleported with a player together by default.

**Comment by ObaniGemini** [comment]
What I noticed is that it is way more noticeable to see when you can't use the function than when you don't have the flag. I personally noticed it while I was at mine :)

**Comment by dnk777** [comment]
Please describe your experience better and more clearly. Btw have you tested the actual version?

**Comment by dnk777** [comment]
Using translocator having a flag (and dropping a flag due to that) is a LEGAL action. I follow the well-known UT translocator behavior usability of which is proven for ages.
